apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: vg-init
  namespace: kube-system
  labels:
    k8s-app: vg-init
spec:
  selector:
    matchLabels:
      name: vg-init
  template:
    metadata:
      labels:
        name: vg-init
    spec:
      tolerations:
        - operator: "Exists"
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
              - matchExpressions:
                  - key: node.humio.com/instance-storage
                    operator: Exists
                  - key: kubernetes.io/arch
                    operator: In
                    values:
                      - amd64
                  - key: kubernetes.io/os
                    operator: In
                    values:
                      - linux
                  - key: eks.amazonaws.com/compute-type
                    operator: NotIn
                    values:
                      - fargate
      containers:
        - name: main
          image: ghcr.io/humio-contrib/instance-storage-init-container/container:v0.3.3
          command: ["/entrypoint.sh"]
          securityContext:
            privileged: true
          resources:
            requests:
              cpu: 100m
              memory: 100Mi
            limits:
              cpu: 200m
              memory: 256Mi
